name: Next.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run Lint
        run: pnpm lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install pnpm
        run: npm install -g pnpm@latest-10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install dependencies
        run: pnpm test

  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: [install, lint, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: pnpm/action-setup@v4
        with:
          version: 10
      
      - name: Install pnpm
        run: npm install -g pnpm@latest-10

      - name: Install dependencies
        run: pnpm install

      - name: Test and coverage
        run: pnpm test --coverage

      - name: Install SonarQube Scanner
        run: pnpm install -g sonarqube-scanner

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=vanillmar_base-app \
            -Dsonar.organization=vanillmar \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.sources=. \
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
            -Dsonar.exclusions=**/*.d.ts, **/types/**, **/__mocks__/**
            -Dsonar.coverage.exclusions=**/__tests__/**,**/hooks/**, **/components/**, **/public/**, **/node_modules/**, sonar.exclusions=**/*.d.ts, **/types/**, **/__mocks__/**

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: [install, lint, test, sonarqube]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses:  pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install
      
      - name: Build Next.js App
        run: pnpm build